baseURL = "http://guidosangiovanni.com"
languageCode = "en-us"
theme="ananke"

[params]
    background_color_class = "bg-white-10"
    description = "The last theme you'll ever need. Maybe."
    featured_image = "/images/header.jpg"
    recent_posts_number = 5
    linkedin = "https://www.linkedin.com/in/guido-sangiovanni/"
    github = "https://github.com/sangio90"
    custom_css = ["css/custom.css"]
