baseurl         = "/"
theme           = "hugo-casper-two"
languageCode    = "en-US"
paginate        = 5

[params]
  title       = "Guido Sangiovanni"
  subtitle    = "...sullo sviluppo Web"

  cover       = "/images/header.jpg"
  description = "Un blog tecnico incentrato sul tema dello sviluppo web."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "sangio90"
  #fbName = "Sangio90"
  githubName = "sangio90"
  linkedinname = "guido-sangiovanni"

  #logo = "hugo-logo.png"
  orgName = "GS"
  orgWebsite = "https://www.guidosangiovanni.com"
  orgDescription = "A full-stack Web Developer"

  author = "GS"
  authorAvatar = "/images/profile.jpeg"
  authorLocation = "Milan, IT"
  #authorWebsite = "https://sangio.github.io"
  #authorDescription = "Describe yourself.."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 100
